name: Github Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - name: Generate docs
        run: |
          cat dts/* > index.d.ts
          deno doc --html --name="Fleek Functions - Global APIs" index.d.ts
          mv index.d.ts docs/
          sed -i "s|$((printf "file://" && realpath index.d.ts) | sed -e "s|/|\&#x2F;|g")|../index.d.ts|g" docs/**/*.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
      - uses: actions/deploy-pages@v4
        id: documentation
